App Backend: Save & Subtract Current Dooley (also tracks swipes)
Bestagons/quack pull request #101
Opened 2021-10-25 03:58 UTC by MimiOlayeye

#69

2021-10-25 14:26 UTC, RafaelPiloto10 requested changes

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/balance_test.py
> +    user_info = [
change to `test_cases`

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/balance_test.py
> +    user_info = [
`user_info` is used twice below and may cause bugs

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/balance_test.py
> +        show_details(Tester)
Instead of verifying by printing, use `assert` to test that `user_info == Tester.FIELD`

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/balance_test.py
> +    for user_info in user_info:
Same here, use `assert` rather than verifying by printing

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/balance_test.py
> +    user_info = [
Same here with `user_info`

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/balance_test.py
> +def main():
no need for main code here, `pytest` will automatically run all of the tests

2021-10-25 14:26 UTC, RafaelPiloto10 commented on app_backend/user.py
> +    """"""
extraneous quotes?

2021-10-31 15:23 UTC, brendacano requested changes
i left some comments that I think could be addressed

2021-10-31 15:23 UTC, brendacano commented on app_backend/balance.py
> +    def __init__(self, name, dooley_dollars, meal_swipes):
I don't know if this matters but maybe you could do like:

`(self, name: string, dooley_dollars: float, meal_swipes: int)`

bc from this it seems like people can enter any value

2021-10-31 15:23 UTC, brendacano commented on app_backend/balance.py
> +        super().__init__(name, dooley_dollars, meal_swipes)
the same goes with this and maybe other parts of your code?

2021-10-31 15:23 UTC, brendacano commented on app_backend/balance.py
> +        self.dooley_dollars = self.dooley_dollars - spent
what if it reaches 0 or goes under 0? should we add a check for that? and same for the mealswipe_sub

2021-10-31 22:20 UTC, MimiOlayeye commented
I made another PR for this ticket (since my branches were messed up for my last PR )
Can I just delete this old PR?

2021-11-01 14:31 UTC, RafaelPiloto10 commented
Closing since you made a new PR

2021-11-01 14:31 UTC, closed without merging