Restructured the backend files. Wrote toggle-favorite
Bestagons/quack pull request #105
Opened 2021-10-25 19:29 UTC by DDavid233

I restructured backend files according to the official documentation [here](https://fastapi.tiangolo.com/tutorial/bigger-applications/). I think we need to use multiple files in our backend, and it's better to start early. The doc is a bit long. Feel free to ask me if there's any part that is not clear.

I also moved the tests to the tests folder and divided tests based on their modules. 

Notice that the URLs for friends APIs are now prefixed with `/friends/`. For example, `/new-friends/` becomes `/friends/new-friends/`.
Similarly, the new one has the URL `/favorites/toggle-favorite/`.

Also, notice that the new API I wrote uses JSON as a means to pass parameters (instead of the query string). Documentations on how to use it can be found [here](https://fastapi.tiangolo.com/tutorial/body/). This is the preferred way as it automatically checks for any incompatible/missing parameters, so that we don't need to write these checks by hand.

2021-10-25 21:16 UTC, RafaelPiloto10 requested changes
Very important work here! Thanks David! I love this new structure! Just a minor thing to keep things consistent with your changes

2021-10-25 21:16 UTC, RafaelPiloto10 commented on app_backend/app/routers/friends.py
> +@router.post("/new-friend/", status_code=status.HTTP_201_CREATED)
Can you re-write this to use the BaseModel preferred method?

2021-10-29 02:52 UTC, RafaelPiloto10 requested changes
Looks good! Thanks again for your work on this!

2021-10-29 02:52 UTC, RafaelPiloto10 commented on app_backend/app/routers/favorites.py
> +    if existing_food_state == favorite.state:
Do we need to error in this case? We don't want to add more complexity to the front end. I think in this case -- return.

Also, write a TODO for setting the food state if it is different

2021-10-30 13:05 UTC, DDavid233 commented on app_backend/app/routers/favorites.py
> +    if existing_food_state == favorite.state:
I agree. A post method should allow repetitions of the same posts.

2021-11-03 18:36 UTC, brendacano approved these changes
I think it all looks good. I like the changes. Im just worried about the other PRs if it will affect them too much if this one gets merged first

2021-11-03 18:36 UTC, brendacano commented on app_backend/app/routers/favorites.py
> +
just a question, are you adding the app_backend/app... directory? and should this branch be merged first so that I could move the stuff I have in the server.py to a new directory/file

2021-11-08 14:05 UTC, DDavid233 commented on app_backend/app/routers/favorites.py
> +
Yeah I can merge this first.

2021-11-08 14:20 UTC, DDavid233 commented
Now rebased to current dev.

2021-11-08 19:53 UTC, RafaelPiloto10 commented
holy guacamole, David, 93 files

2021-11-08 20:01 UTC, RafaelPiloto10 requested changes
I don't think this PR is a good idea -- 93 files changed sounds like an error. Can you please split this PR up into the following:

- backend restructure
- toggle favorites backend
- toggle favorites frontend

I know that is tedious, but it's going to be impossible to properly review the 93 files.
When you make these PR's think about how you want to chain them -- which PR depends on which and which should be merged first.

I am hesitant to approve to merge this given how many files changed in just 1 PR

2021-11-11 18:27 UTC, DDavid233 commented
It is probably because I merged the development branch into my branch. I was hoping rebase will reduce the commit amount, but apparently that didn't do it.

2021-11-11 18:29 UTC, RafaelPiloto10 commented
> It is probably because I merged the development branch into my branch. I was hoping rebase will reduce the commit amount, but apparently that didn't do it.

Try reverting the rebase and do `git pull origin dev`. This happened to Ore and doing that fixed it

2021-11-11 19:30 UTC, DDavid233 commented
OK I guess now it's better :)
Will fix the failing test later.

2021-11-11 20:10 UTC, brendacano commented
> OK I guess now it's better :) Will fix the failing test later.

If you are ever worried that the merging or anything isn't good, you could always just start fresh in a new branch from dev and edit in everything you were doing. I know its a bit more work but at least you can be sure that its correct

2021-11-17 04:15 UTC, RafaelPiloto10 approved these changes
Top priority, let's merge this asap

2021-11-17 04:16 UTC, RafaelPiloto10 requested changes
Missed the failing tests - lets fix the tests first and then merge this asap lol

2021-11-17 04:25 UTC, DDavid233 commented
I'm not sure why, but it looks like the register test creates users in the production database (when it shouldn't).

2021-11-17 04:30 UTC, DDavid233 commented
I think I found the cause

2021-11-17 04:32 UTC, RafaelPiloto10 commented
If you're not seeing the `Dry run enabled, not updating` print message then its not using the TestDatabase class in `server_test.py`

2021-11-17 04:57 UTC, DDavid233 commented
I am removing TestDatabase class and using an environment variable to identify whether the server is running in test mode.

2021-11-17 05:05 UTC, RafaelPiloto10 approved these changes

2021-11-17 05:05 UTC, RafaelPiloto10 commented on app_backend/database.py
> +db = Database(os.getenv("DB_USERNAME"), os.getenv("DB_PASSWORD"), test_mode="pytest" in sys.modules)
Clever! Looks good to me!

2021-11-17 13:34 UTC, merged