Save seated section (app backend) (corrected)
Bestagons/quack pull request #117
Opened 2021-10-31 23:04 UTC by MimiOlayeye

2021-11-01 14:13 UTC, RafaelPiloto10 requested changes
Some minor nits. Great job!

2021-11-01 14:13 UTC, RafaelPiloto10 commented on app_backend/seat_test.py
> +        if (0< sections <=9): # Success Cases
nit: spacing

2021-11-01 14:13 UTC, RafaelPiloto10 commented on app_backend/seat_test.py
> +        Test_success =  Tester.set_section_info(sections)
nit: variables should be named in lowercase

2021-11-01 14:15 UTC, RafaelPiloto10 requested changes

2021-11-01 14:15 UTC, RafaelPiloto10 commented on app_backend/sections.py
> +    section_dict = {1: "red",
nit: consider rename to `color_dict` or something along that line

2021-11-01 14:16 UTC, RafaelPiloto10 commented
Remember to set the merge base when creating a pull request to `dev`

2021-11-01 16:01 UTC, MimiOlayeye commented
Looks like I'll have to make another branch. My current branch is based on production :(

2021-11-01 18:28 UTC, RafaelPiloto10 commented
@MimiOlayeye you should be good -- the only files changed in this PR is the 3 you edited. I just meant that when you create a PR you have to specify what branch you want to merge your changes with, which should always be dev.

If you want to create a new branch, make sure you are always in `dev` to start and then create the new branch with `checkout -b <branch-name>`

2021-11-01 18:31 UTC, RafaelPiloto10 approved these changes

2021-11-01 18:39 UTC, MimiOlayeye commented
Got it thanks!

2021-11-01 19:27 UTC, DDavid233 approved these changes
Looks good. Is this the fast API backend part? Looks like there's no fast API code.

2021-11-01 19:34 UTC, MimiOlayeye commented
@DDavid233 no its app-backend

2021-11-02 16:19 UTC, RafaelPiloto10 commented
Good point @DDavid233, even though it is app-backend, we still need a way for the front end to alert the app-backend that we want it to save the seating function. @MimiOlayeye, do you think you could add a route for the app-backend to save the seated section? AKA implement your seated section code

2021-11-03 19:17 UTC, Foxworth22 approved these changes
What are we waiting on to merge this? @MimiOlayeye

2021-11-03 19:38 UTC, merged